[server]
host = "127.0.0.1"
port = 8080

[secret]
jwt_secret = "ilovemila"
password_salt = "supersafekids"

[database]
username = "root"
password = "root"
url = "localhost:8000"
namespace = "namespace"
database = "database"
